apiVersion: v1
kind: Pod
metadata:
  name: pod-containers
  labels:
    name: pod-containers
spec:
  containers:
  - name: containers-1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: containers-2
    image: alpine
    command: ["watch", "wget", "-q0-", localhost]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
   