apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    imageregistry: "https://hub.docker.com"
spec:
  containers:
  - name: container01
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
