version: '2'
services:
  web:
    image: jtarciso/site-treinamentos:v3
    #build: .
    container_name: site
    restart: always
    ports:
      - '8023:80'

  web2:
    image: jtarciso/site-treinamentos:v2
    #build: .
    container_name: site2
    restart: always
    ports:
    - '8024:80'