additionalArguments:
  - "--accesslog=true"
  - "--accesslog.format=json"
  - "--log.level=DEBUG"

deployment:
  replicas: 1

service:
  spec:
    loadBalancerIP: 20.227.27.142
  annotations:
    "service.beta.kubernetes.io/azure-load-balancer-resource-group": "rg-basic"
