apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
  spec:
        containers:
          - name: app-web
            image: nginx